name: Update Stats in README.md
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: fetch-stats
        run: curl -sf https://api.johnbot.app/status/stats -o stats.json
      - name: Update README.md
        run: |
          sudo apt-get update -qq && sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          users=$(jq -r '.data.users' stats.json)
          guilds=$(jq -r '.data.guilds' stats.json)
          users_fmt=$(printf "%'d" "$users")
          guilds_fmt=$(printf "%'d" "$guilds")
          sed -i -E "s/used by [0-9,]+ users \(over [0-9,]+ servers/used by $users_fmt users (over $guilds_fmt servers/" profile/README.md
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add stats.json profile/README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update stats in README.md"
          git push
